exclude: "^{{cookiecutter\\.project_name}}/"
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-json
        - id: check-merge-conflict
        - id: check-yaml
        - id: end-of-file-fixer
        - id: pretty-format-json
          name: pretty-format-json
          entry: pretty-format-json --autofix
          language: python
          types: ["json"]
        - id: trailing-whitespace
